[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"
authors = ["it"]

[lib]
name = "util"
path = "src/util.rs"

[[bin]]
name = "day_1"
path = "src/solutions/day_1.rs"

[[bin]]
name = "day_2"
path = "src/solutions/day_2.rs"
